version: '3.8'

services:
  # Web应用服务
  app:
    build: .
    container_name: ai-model-platform-app
    restart: always
    ports:
      - "8000:8000"
    depends_on:
      - db
      - redis
    volumes:
      - ./uploads:/app/uploads
      - ./.env:/app/.env
    environment:
      - DATABASE_URL=postgresql+asyncpg://postgres:postgres@db:5432/aiplatform
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    networks:
      - app-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/api/v1/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  # 数据库服务
  db:
    image: postgres:13-alpine
    container_name: ai-model-platform-db
    restart: always
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=aiplatform
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - app-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  # Redis缓存和消息队列
  redis:
    image: redis:6-alpine
    container_name: ai-model-platform-redis
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    command: redis-server --appendonly yes
    networks:
      - app-network
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

  # pgAdmin管理面板（可选，用于开发环境）
  pgadmin:
    image: dpage/pgadmin4
    container_name: ai-model-platform-pgadmin
    restart: always
    ports:
      - "5050:80"
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@example.com
      - PGADMIN_DEFAULT_PASSWORD=admin
    volumes:
      - pgadmin-data:/var/lib/pgadmin
    depends_on:
      - db
    networks:
      - app-network
    profiles:
      - dev

volumes:
  postgres-data:
    name: ai-model-platform-pg-data
  redis-data:
    name: ai-model-platform-redis-data
  pgadmin-data:
    name: ai-model-platform-pgadmin-data

networks:
  app-network:
    name: ai-model-platform-network 