version: '3.8'

# 生产环境特定配置
services:
  app:
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - APP_ENV=production
      - APP_DEBUG=false
    deploy:
      replicas: 2
      resources:
        limits:
          cpus: '1'
          memory: 1G
    # 使用内置的入口点脚本，而不是命令重写

  db:
    restart: always
    environment:
      - POSTGRES_PASSWORD=${DB_PASSWORD:-postgres}  # 从环境变量获取密码
    volumes:
      - postgres-data:/var/lib/postgresql/data
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 1G

  redis:
    restart: always
    volumes:
      - redis-data:/data
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 512M

  # 生产环境中删除pgAdmin，替换为仅在内部网络可访问的Nginx代理
  nginx:
    image: nginx:alpine
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d
      - ./nginx/ssl:/etc/nginx/ssl
      - ./nginx/logs:/var/log/nginx
    depends_on:
      - app
    networks:
      - app-network 